version: '2'
volumes:
  jiminy:
  jiparm:
services:
  app:
    #container_name: voivi_app
    build: .
    ports:
    - "10101:10101"
    #volumes:
    # - .:/code
    #links:
    #- db
    depends_on:
    - db
  db:
    #container_name: voivi_database
    image: library/mongo:3.2.8
    #command: mongod -f /etc/mongo.conf
    volumes:
    - jiminy:/data/db
    - jiparm:/data/configdb
    #- ./docker/mongo/db:/data/db
    #- ./docker/mongo/log:/log
    #- ./docker/mongo/mongod.cfg:/etc/mongo.conf
    ports:
    - "27017:27017"
    #restart: always
