apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web
  name: web-controller
spec:
  replicas: 1
  selector:
    name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: gcr.io/jiminy-standalone/jiminy:v6
        name: web
        ports:
        - containerPort: 10101
          name: http-server
