version: '2'
volumes:
  jenkinshd:
  sonarhd:
  sonarhq:
services:
  jenkins:
    container_name: jenkins
    image: library/jenkins:2.7.1-alpine
    volumes:
    - jenkinshd:/var/jenkins_home
    - ../:/home/voivi/
    #docker cp jenkinshd:/var/log/jenkins/jenkins.log jenkins.log
    ports:
    - "8080:8080"
    - "50000:50000"

  sonar:
    container_name: sonar
    image: library/sonarqube:5.6-alpine
    volumes:
    - sonarhd:/opt/sonarqube/data
    - sonarhq:/opt/sonarqube/extensions
    #- ../:/home/voivi/
    ports:
    - "9000:9000"
    - "9002:9002"
