#FROM library/mongo:3.2.8
#FROM library/jenkins:2.7.1-alpine
#FROM library/sonarqube:5.6-alpine 

# Add a user that can `sudo`.
#RUN useradd -m user \
#&& echo "user ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/user

# Don't be root.
# RUN useradd -ms /bin/ash user

#docker build -t my-java-app .
#docker run -it --rm --name my-running-app my-java-app
#docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp java:7 javac Main.java
